version: '3.3'

services:
  django:
    build: .
    env_file:
      - ./.env
    stop_signal: SIGINT
    container_name: django
    command: bash -c "sleep 15s;
      cd backend;
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py createsuperuser --noinput;
      python manage.py runserver 0.0.0.0:8000;"
    volumes:
      - ./dump/app:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db


  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgis/postgis:17-3.4-alpine
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
    env_file:
      - ./.env
    volumes:
      - ./dump/postgres_db/postgres/postgresql-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./dump/pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped


networks:
  backend:
    driver: bridge